spring:
  main:
    web-application-type: none
    banner-mode: off
    lazy-initialization: true
  application:
    name: agile-console
  profiles:
    active: engine, default
  jmx:
    enabled: false
logging:
  level:
    root: WARN
