server:
  port: 9010
  forward-headers-strategy: native
  compression:
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://DB_HOST:DB_PORT/DB_NAME?useSSL=false&characterEncoding=UTF-8&cachePrepStmts=true&useServerPrepStmts=true&prepStmtCacheSize=200&prepStmtCacheSqlLimit=2048&rewriteBatchedStatements=true&useLegacyDatetimeCode=false
    username: DB_USER
    password: DB_PASSWORD
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: false
        format_sql: false
    show-sql: true
  flyway:
    enabled: false # 不自动初始化数据库
    clean-disabled: false # 禁止清理数据库表
    baseline-on-migrate: false # 如果不是项目初期引入，而是在数据库已有表的情况下引入时必须设置 true
    locations: # 数据库脚本所在地址
  cache:
    type: caffeine # 缓存类型，默认使用 caffeine

springdoc:
  api-docs:
    enabled: false # 是否开启 API 文档

agile:
  database:
    table-prefix: 数据表名前缀
  spring:
    upload:
      driver-name: 使用的上传驱动 # aliyun-oss, tencent-cos, local-file
      aliyun-oss:
        access-key-id: 阿里云 OSS accessKeyId
        access-key-secret: 阿里云 OSS accessKeySecret
        endpoint: 阿里云 OSS 数据中心访问域名
        bucket: 阿里云 OSS Bucket
        directory: 阿里云文件目录
        style-delimiter: "" #图片样式分割符号，默认为空
      tencent-cos:
        app-id: 腾讯云 COS appId
        secret-id: 腾讯云 COS secretId
        secret-key: 腾讯云 COS secretKey
        bucket: 腾讯云 COS 存储桶空间名称
        region: 腾讯云 COS 所属区域
        directory: 腾讯云文件目录
        style-delimiter: "!" #图片样式分割符号，默认 ! 叹号
      local-file:
        access-path: 上传文件访问路径 # 比如 /files/** 或者使用 nginx 代理直接写 URL https://agile.huijiewei.com/files
        upload-path: 上传目录 # 使用相对路径 ./files 或者绝对路径
        corp-action: /open/crop-image # 图片切割 action
        upload-action: /open/upload-file # 图片上传 action
        policy-key: 自定义密钥 # 必须是16位长度

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE