spring:
  application:
    name: agile-serve-admin
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: engine, default
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  jmx:
    enabled: false
  main:
    lazy-initialization: true
  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    enabled: false