spring:
  application:
    name: agile-serve-admin
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 30
        jdbc:
          batch_size: 30
          fetch_size: 30
          time_zone: Asia/Shanghai
          batch_versioned_data: true
      javax:
        persistence:
          validation:
            mode: none
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 20
        size-parameter: size
        page-parameter: page
        one-indexed-parameters: true
  datasource:
    hikari:
      max-lifetime: 120000
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: default
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  jmx:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Shanghai

agile:
  format:
    date-format: yyyy-MM-dd
    time-format: HH:mm
    datetime-format: yyyy-MM-dd HH:mm